### ISSUE TITLE
Error when setting and item where a dictionary is nested in a list

### ISSUE THREAD

**Issue by ophiry** [gmr/flatdict#21]
here: https://github.com/gmr/flatdict/blob/3.0.0/flatdict.py#L402 it assumes that if a nested object is an array, the tail of the path needs to be an int. but if the path includes other path elements after the list index, it will fail

example:
```
d = FlatterDict({'a':[{'b':1}]})
d['a:0:b'] # this works
d['a:0:b'] = 4 # this fails
```

**Comment by gmr** [comment]
This is fixed in 3.1

**Comment by gmr** [comment]
So the enhancement would be to allow for positional offset accessors, then traversing into sub FlatterDict objects.

Seems reasonable, happy to have a PR and will add to my own-to-do list if something doesn't come in.

**Comment by mileslucas** [comment]
I actually realize, now, that this does not solve the precise issue of setting items and updating, but rather only fixes `as_dict()` for these items.

**Comment by wsantos** [comment]
@gmr I think we can close this one, the last prs you've merged fixed the issue.

**Comment by gmr** [comment]
Thanks
